routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'AboutController@index');


Auth::routes();

Route::get('/home', 'ProductController@index');

Route::resource('products', 'ProductController');

Route::resource('orders', 'OrderController');

Route::resource('contacts', 'ContactController');

Route::resource('about', 'AboutController');	

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $fillable = [
    'title', 
    'description',
     'price', 
     'photo', 
     'type'];
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    public function __construct() {
        $this->middleware('auth.admin')
            ->except(['index', 'show', ]);

        $this->middleware('auth')->except(['index', 'show']);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::all();
        return view('product.index', compact('products'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('product.form');
        return redirect()->route('products.index');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Product::create([
            'title' => $request->get('title'),
            'photo' => $request->get('photo'),
            'description' => $request->get('description'),
            'price' => $request->get('price'),
            'type' => $request->get('type'),
            ]);
        return redirect()->route('products.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show($product)
    {
        $products = Product::find($product);
        return view('product.show', compact('products'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $products = Product::find($id);
        return view('product.form', compact('products'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        Product::find($id)->update($request->all());
        return redirect()->route('products.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Product::find($id)->delete();
        return redirect()->route('products.index');
    }
}

resources/views/product/form.blade.php
 @extends('layouts.app')
 
 @section('content')
<div class="container">
 
		@if(isset($products))
		<h2>Produkto - {{$products->title}} - tvarkymas</h2>
		{!! Form::model($products, ['route' => ['products.update', $products->id], 'method' => 'put']) !!}
		@else
		{!! Form::open(['route' => ['products.store'], 'method' => 'POST']) !!}
		@endif
	
 
	<div class="form-group">
	<h4>Antraštė</h4>
	{!! Form::text('title', null) !!}
	</div>
 
	<div class="form-group">
	<h4>Aprašymas</h4>
	{!! Form::textarea('description', null) !!}
	</div>
 
	<div class="form-group">
	<h4>Kaina</h4>
	{!! Form::text('price', null) !!}
	</div>

	<div class="form-group">
	<h4>Tipas(kategorija)</h4>
	{!! Form::text('type', null) !!}
	</div>
	
	<div class="form-group">
	<h4>Nuotrauka</h4>
	{!!Form::text('photo', null, ['class' => 'form-control']) !!}
	</div>
	



	{!! Form::submit('Saugoti', ['class' => 'btn btn-primary']) !!}
	{!! Form::close() !!}

	@if(Auth::user() && Auth::user()->isAdmin())
		@if(isset($products))


		{!! Form::open(['route'=> ['products.destroy', $products->id], 'method' => 'DELETE']) !!}
		{!! Form::submit('Trinti', ['class' => 'btn btn-danger']) !!}
		@endif



		{!! Form::close() !!}
	@endif
</div>
 @endsection

resources/views/product/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<div class="connectbtnhover">
		<a href="{{ route('orders.create') }}" class="connectbtn col-md-offset-5"><i class="fa fa-envelope" aria-hidden="true"></i> Turite klausimų?</a>
	</div>

<h2><strong>Produktai</strong></h2>
	@foreach($products->chunk(3) as $chunk)
	<div class="row">

		@foreach($chunk as $product)
			<div class="col-md-4">
				<div class="thumbnail">

					<a href ="{{ route('products.show', $product->id) }}"><img src="{{ $product->photo }}"></a>
					<p><strong>{{ $product->title }}</strong></p>
 						<p><strong>{{ $product->description }}</strong></p>
						<p><strong>Kaina: {{ $product->price }} Eur </strong></p>
						@if(Auth::user() && Auth::user()->isAdmin())
							<a href="{{ route('products.edit', $product->id) }}" class="btn btn-success">Keisti</a>
						@endif
 					</div>
 				</div>
 		@endforeach
					
	</div>
	@endforeach
				
</div>
@endsection

resources/views/product/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-offset-3 thumbnail">
			<h3><strong>{{ $products->title }}</strong></h3>

			<img src="{{ $products->photo }}" class="img-responsive" width="500" >
			<p><strong>{{$products->description}}</strong></p>
			<ul>
				<li><strong>Price: {{$products->price}} eur</strong></li>
				<li><strong>Quantity: {{$products->quantity}} eur</strong></li>
			</ul>
		</div>
	</div>
</div>
@endsection