routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'AboutController@index');


Auth::routes();

Route::get('/home', 'ProductController@index');

Route::resource('products', 'ProductController');

Route::resource('orders', 'OrderController');

Route::resource('contacts', 'ContactController');

Route::resource('about', 'AboutController');	

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
   	protected $fillable = [
    	'name', 'email', 'phone', 'comment', 'address'
    	];
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use App\Order;
use App\About;
use Illuminate\Http\Request;

class OrderController extends Controller
{


    public function __construct() {
        $this->middleware('auth.admin')
            ->except(['index', 'show', 'store', 'create']);

        $this->middleware('auth')->except(['store', 'create']);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $orders = Order::all();
        return view('order.index', compact('orders'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('order.form');
        return redirect()->route('orders.index');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Order::create([
            'name' => $request->get('name'),
            'email' => $request->get('email'),
            'phone' => $request->get('phone'),
            'comment' => $request->get('comment'),
            'address' => $request->get('address'),
            ]);
        return redirect()->route('about.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function show(Order $order)
    {
        $order = Order::find($order);
        return view('order.show', compact('order'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $orders = Order::find($id);
        return view('order.form', compact('orders'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        Order::find($id)->update($request->all());
        return redirect()->route('orders.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Order::find($id)->delete();
        return redirect()->route('orders.index');
    }
}

resources/views/Order/form.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	@if(isset($orders))
		<h2>Užsakymo taisymas - {{$orders->name}}</h2>
		{!! Form::model($orders, ['route' => ['orders.update', $orders->id], 'method' => 'put']) !!}
	@else
		{!! Form::open(['route' => ['orders.store'], 'method' => 'POST']) !!}
		<h2 class="thumbnail">Klauskite kas domina, su jumis susisieksime kelių valandų bėgyje.</h2>
	@endif

	<div class="form-group">
		<h4>Vardas</h4>
		{!! Form::text('name', null) !!}
	</div>

	<div class="form-group">
		<h4>Namų adresas</h4>
		{!! Form::text('address', null) !!}
	</div>

	<div class="form-group">
		<h4>Elektroninis paštas</h4>
		{!! Form::text('email', null) !!}
	</div>

	<div class="form-group">
		<h4>Phone</h4>
		{!! Form::text('phone', null) !!}
	</div>

	<div class="form-group">
		<h4>Komentaras</h4>
		{!! Form::textarea('comment', null) !!}
	</div>

	

	{!! Form::submit('Išsaugoti', ['class' => 'btn btn-primary']) !!}
	{!! Form::close() !!}

	@if(Auth::user() && Auth::user()->isAdmin())
		@if(isset($orders))


		{!! Form::open(['route'=> ['orders.destroy', $orders->id], 'method' => 'DELETE']) !!}
		{!! Form::submit('Ištrinti', ['class' => 'btn btn-danger']) !!}



		{!! Form::close() !!}
		@endif
	@endif
</div>
@endsection

resources/views/Order/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
<h2>Užsakymai</h2>
	@foreach($orders->chunk(3) as $chunk)
	<div class="row">
		@foreach($chunk as $order)
			<div class="col-md-4">
				<div class="thumbnail">
					<a href ="{{ route('orders.show', $order->id) }}"><p>{{ $order->name }}</p></a>
 						
 						<p>{{ $order->phone }}</p>
 						<p>{{ $order->created_at }}</p>
 						@if(Auth::user() && Auth::user()->isAdmin())
							<a href="{{ route('orders.edit', $order->id) }}" class="btn btn-success">Keisti</a>
						@endif
						
 					</div>
 				</div>
 		@endforeach
					
	</div>
	@endforeach
				
</div>
@endsection

resources/views/Order/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-10  thumbnail">
			<h2>{{ $order->name }}</h2>
			<ul>
				<li>Elektorninis paštas: {{$order->email}} </li>	
				<li>Adresas: {{ $order->address }} eur</li>			
				<li>{{ $order->email }}</li>
				<li>Klausimai: {{ $order->comment }}</li>

			</ul>
		</div>
	</div>
</div>
@endsection