routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'AboutController@index');


Auth::routes();

Route::get('/home', 'ProductController@index');

Route::resource('products', 'ProductController');

Route::resource('orders', 'OrderController');

Route::resource('contacts', 'ContactController');

Route::resource('about', 'AboutController');	

app/About.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class About extends Model
{
    protected $fillable = ['title', 'comment' ];
}

app/Http/Controllers/AboutController.php
<?php

namespace App\Http\Controllers;

use App\About;
use Illuminate\Http\Request;

class AboutController extends Controller
{

     public function __construct() {
        $this->middleware('auth.admin')
            ->except(['index', 'show', 'edit','store']);

        $this->middleware('auth')->except(['index', 'show']);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $abouts = About::all();
        return view('about.index', compact('abouts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('about.form');
        return redirect()->route('about.index');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        About::create([
            'title' => $request->get('title'),
            'comment' => $request->get('comment'),
            ]);
        return redirect()->route('about.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\About  $about
     * @return \Illuminate\Http\Response
     */
    public function show(About $about)
    {
        return view('about.show', compact('about'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\About  $about
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $abouts = About::find($id);
        return view('about.form', compact('abouts'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\About  $about
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        About::find($id)->update($request->all());
        return redirect()->route('about.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\About  $about
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        About::find($id)->delete();
        return redirect()->route('about.index');
    }
}

resources/views/About/form.blade.php
@extends('layouts.app')

@section('content')
<div class="container">

	@if(isset($abouts))
		<h2>Užsakymo taisymas - {{$abouts->name}}</h2>
		{!! Form::model($abouts, ['route' => ['about.update', $abouts->id], 'method' => 'put']) !!}
	@else
		{!! Form::open(['route' => ['about.store'], 'method' => 'POST']) !!}
	@endif

	<div class="form-group">
		<h4>Antraštė</h4>
		{!! Form::text('title', null) !!}
	</div>

	<div class="form-group">
		<h4>Komentaras</h4>
		{!! Form::textarea('comment', null) !!}
	</div>





	{!! Form::submit('save', ['class' => 'btn btn-primary']) !!}
		{!! Form::close() !!}

		
		@if(isset($abouts))


			{!! Form::open(['route'=> ['about.destroy', $abouts->id], 'method' => 'DELETE']) !!}
			{!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}



		{!! Form::close() !!}
		@endif
</div>
 @endsection

resources/views/About/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
		@foreach($abouts->chunk(1) as $chunk)
	<div class="row">
		@foreach($chunk as $about)
			<div class="col-md-12">
				<div class="thumbnail aboutUs">
 						<h3><strong>{{ $about->title }}</strong></h3>
 						<p><strong>{{ $about->comment }}</strong></p>
 						@if(Auth::user() && Auth::user()->isAdmin())
						<a href="{{ route('about.edit', $about->id) }}" class="btn btn-success">Keisti</a>
						@endif
 					</div>
 				</div>
 		@endforeach
					
	</div>
	@endforeach

</div>
@endsection